### ISSUE TITLE
Change location/multiple locations for the com.mojang folder?

### ISSUE THREAD

**Issue by Mcfly2340** [ShortDevelopment/VB-Audio-Router#19]
Because I'm using a version switcher for bedrock, I'd like to be able to change the folder location to see the worlds on that particular profile of my version switcher.

**Comment by ShortDevelopment** [comment]
@Mcfly2340 Sorry, I think I linked the wrong repo.
You can open an issue over at [ShortDevelopment/MC-Manager](https://github.com/ShortDevelopment/MC-Manager/issues)
